name: Deploy

on:
  repository_dispatch:
    types:
      - deploy-pages

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: Deploy

    runs-on: ubuntu-latest
    
    steps:
      - name: Verify artifact
        env:
          TOKEN: ${{ secrets.GH_NODE_DEPLOY_TOKEN }}
        run: |
          curl \
            -H "Authorization: Bearer $TOKEN" \
            "https://api.github.com/repos/$REPO/actions/artifacts/$ARTIFACT"

      - name: Download artifact
        env:
          TOKEN: ${{ secrets.GH_NODE_DEPLOY_TOKEN }}
        run: |
          REPO="${{ github.event.client_payload.source_repo }}"
          ARTIFACT="${{ github.event.client_payload.artifact_id }}"
      
          curl -L \
            -H "Authorization: Bearer $TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$REPO/actions/artifacts/$ARTIFACT/zip" \
            -o artifact.zip
      
          unzip artifact.zip -d site

      - name: Inspect files
        run: |
          pwd
          ls -lah
          find site

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: site
      
      - name: Deploy
        uses: actions/deploy-pages@v4
